version: '3'
services:
  af-backup:
    image: index.docker.io/industrialcloud/af-backup-2:latest
    command: sh
    tty: true
    stdin_open: true
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    external: true
