services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app
    tty: true
    stdin_open: true
    
networks:
  app:
    external: true
