services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app
    volumes:
      - ./agile-factory:/agile
    
networks:
  app:
    external: true
