version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh
    tty: true
    stdin_open: true
    volumes:
      - ./dist:/app
    env_file:
      - .env
    networks:
      - app

networks:
  app:
