version: '3'
services:
  af-backup:
    restart: unless-stopped
    image: index.docker.io/industrialcloud/af-backup-2:v1.7.3
    volumes:
      - /home/$USER/agile-factory/:/agile
    env_file:
      - backup.env
    networks:
      - traefik
      - app

networks:
  traefik:
    external: true
  app:
    external: true
